FULL_OPEN = "O"
FULL_CLOSE = "C"
HOLD_STATE = "H"
READ_PRESSURE = "R5"
READ_VALVE_POSITION_PERCENT = "R6"
READ_TARGET_PRESSURE = "R1"
WRITE_TARGET_PRESSURE = "S1"
START_REGULATION = "D1"
WRITE_TARGET_PERCENT = "S2"
KEEP_TARGET_PERCENT = "D2"

MIN_PRESSURE_BORDER = 0.0
MAX_PRESSURE_BORDER = 133.3
MAX_SET_PRESSURE = 100.0
