FULL_OPEN = "O"
FULL_CLOSE = "C"
READ_PRESSURE = "R5"
READ_VALVE_POSITION_PERCENT = "R6"
READ_TARGET_PRESSURE = "R1"
WRITE_TARGET_PRESSURE = "S1"
START_REGULATION = "D1"

MIN_PRESSURE_BORDER = 0.0
MAX_PRESSURE_BORDER = 133.3
