RRG_READ_VALUE = "MFC_READ"
RRG_WRITE_VALUE = "MFC_WRITE"
THROTTLE_FULL_OPEN = "THROTTLE_FULL_OPEN"  # "O"
THROTTLE_FULL_CLOSE = "THROTTLE_FULL_CLOSE"  # "C"
THROTTLE_READ_PRESSURE = "THROTTLE_READ_PRESSURE"  # "R5"
THROTTLE_READ_POSITION_PERCENT = "THROTTLE_READ_POSITION"  # "R6"
THROTTLE_READ_TARGET_PRESSURE = "THROTTLE_READ_TARGET_PRESSURE"  # "R1"
THROTTLE_WRITE_TARGET_PRESSURE = "THROTTLE_WRITE_TARGET_PRESSURE"  # "S1"
THROTTLE_START_REGULATION = "THROTTLE_START"  # "D1"
THROTTLE_STOP_REGULATION = "THROTTLE_STOP"  # New command
# Аналог S2+D2, но не в %, а в шагах + сразу удержание уставки
THROTTLE_MOVE_TARGET_POSITION = "THROTTLE_MOVE_TARGET_POSITION"  # "S2"
# KEEP_TARGET_PERCENT = "D2"

MIN_PRESSURE_BORDER = 0.0
MAX_PRESSURE_BORDER = 133.3

FULL_OPEN_THROTTLE_BORDER = 99.7
FULL_CLOSE_THROTTLE_BORDER = 0.3

TOTAL_THROTTLE_STEPS = 40000
